# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'urban-dictionary-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for urban-dictionary-ios
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
end
