# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'push-notifications-live' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for push-notifications-live
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'AmplifyPlugins/AWSAPIPlugin'
end
